name: drupal-site
recipe: drupal9
config:
  php: 8.1
  webroot: web
  config:
    php: .lando/php.ini
proxy:
  appserver:
    - ethan-drupal-1.lndo.site
services:
  phpmyadmin:
    type: phpmyadmin:5.0
    hosts:
      - database