<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 *
 * Defines the theming capabilities provided by this module.
 */
function hook_hello_world_theme($existing, $type, $theme, $path) {
  return array(
    'hello_world_content_array' => array(
      // We use 'render element' when the item to be passed is a self-describing
      // render array (it will have #theme_wrappers)
      'render element' => 'element',
    ),
    'hello_world_list' => array(
      // We use 'variables' when the item to be passed is an array whose
      // structure must be described here.
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
      ),
    ),
    'hello_world_example_form'  => array(
      'render element' => 'form',
      // In this one the rendering will be done by a template file
      // (theming-example-text-form.tpl.php) instead of being rendered by a
      // function. Note the use of dashes to separate words in place of
      // underscores. The template file's extension is also left out so that
      // it may be determined automatically depending on the template engine
      // the site is using.
      'template' => 'hello-world-text-form',
    ),
  );
}


